In [49]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats as st
import statsmodels.tsa as ts

from sklearn.metrics import mean_squared_error
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

%matplotlib inline
plt.style.use("ggplot")
sns.set_context("talk")

In [79]:
data = pd.read_csv("data/M4_data.csv", index_col="date")[:72]

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72 entries, 1/31/03 to 12/31/08
Data columns (total 1 columns):
cpi    72 non-null float64
dtypes: float64(1)
memory usage: 1.1+ KB


In [81]:
data.describe()

cpi
count  72.000000
mean    3.581944
std     1.896370
min     0.460000
25%     2.100000
50%     3.055000
75%     5.335000
max     9.170000

In [85]:
p = 2
d = 0
q = 0
horizon=4
window = 50

In [86]:
# expansion
forecast = []
for i in range(0, len(data)-window+1):
    data_use = data[0:i+window]
    model = ts.arima_model.ARIMA(endog=data_use, order=(p, d, q)).fit()
    horizon_forecast = model.forecast(steps=horizon)
    forecast.append(horizon_forecast[0][horizon-1])
    
result = pd.concat([pd.DataFrame(data[window+horizon-1:]), 
                    pd.DataFrame(forecast[:-horizon], index=pd.DataFrame(data[window+horizon-1:]).index)], 
                   axis=1)
result.rename(columns={"cpi":"actual", 0:"forecast"}, inplace=True)

/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:191: FutureWarning: Creating a DatetimeIndex by passing range endpoints is deprecated.  Use `pandas.date_range` instead.
  start=index[0], end=index[-1], freq=freq)
/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency informat

In [89]:
result.shape

(19, 2)

In [87]:
np.sqrt(mean_squared_error(result.actual, result.forecast))

2.796225689848686

In [94]:
p = 1
d = 0
q = 0
horizon=6
window = 36

In [98]:
# rolling
forecast = []
for i in range(0, len(data)-window+1):
    data_use = data[i:i+window]
    model = ts.arima_model.ARIMA(endog=data_use, order=(p, d, q)).fit()
    horizon_forecast = model.forecast(steps=horizon)
    forecast.append(horizon_forecast[0][horizon-1])
    
result = pd.concat([pd.DataFrame(data[window+horizon-1:]), 
                    pd.DataFrame(forecast[:-horizon], index=pd.DataFrame(data[window+horizon-1:]).index)], 
                   axis=1)
result.rename(columns={"cpi":"actual", 0:"forecast"}, inplace=True)

/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency M wil

In [101]:
np.sqrt(mean_squared_error(result.actual, result.forecast))

2.7734044532354525

## Question 4.49

Estimate an AR(1) model of ygr on its first lag and a constant by changing the forecast model (locate the "Run your forecast model here" and change the equation "equation eq1.ls {%v} c {%v}(-1) {%v}(-2)" to "equation eq1.ls {%v} c {%v}(-1)"). We will use an AR(1) model throughout this exercise since more realistic models have not been discussed yet. 

We will first evaluate forecast performance of the AR(1) model using an expanding strategy (so set !strategy_rolling=0 in the code). Run the strategy for 21 estimation samples by setting !num_rolling =21 (the maximum possible is 22, because data for 2014q4 is not available).

a) What is the implied MAE of this forecast strategy for half of a year ahead? Please enter the answer up to 3 decimals, no rounding.

In [103]:
india = pd.read_csv("data/India_Q.csv")

In [105]:
india

dateid01                   dateid      rgdp        ygr
0   2003-01-01  2003-03-31 23:59:59.999   7028.06   3.210846
1   2003-04-01  2003-06-30 23:59:59.999   7221.13   5.046689
2   2003-07-01  2003-09-30 23:59:59.999   7412.13   7.369267
3   2003-10-01  2003-12-31 23:59:59.999   7748.63  11.823654
4   2004-01-01  2004-03-31 23:59:59.999   7635.01   8.636096
5   2004-04-01  2004-06-30 23:59:59.999   7841.48   8.590761
6   2004-07-01  2004-09-30 23:59:59.999   8060.99   8.754029
7   2004-10-01  2004-12-31 23:59:59.999   8148.17   5.156266
8   2005-01-01  2005-03-31 23:59:59.999   8334.76   9.165017
9   2005-04-01  2005-06-30 23:59:59.999   8578.76   9.402307
10  2005-07-01  2005-09-30 23:59:59.999   8717.41   8.143169
11  2005-10-01  2005-12-31 23:59:59.999   8914.83   9.408984
12  2006-01-01  2006-03-31 23:59:59.999   9169.71  10.017685
13  2006-04-01  2006-06-30 23:59:59.999   9231.55   7.609375
14  2006-07-01  2006-09-30 23:59:59.999   9583.48   9.934946
15  2006-10-01  2006-12-31 23:59:59.999   9790.03   9.817349
16  2007-01-01  2007-03-31 23:59:59.999  10057.94   9.686566
17  2007-04-01  2007-06-30 23:59:59.999  10229.08  10.805661
18  2007-07-01  2007-09-30 23:59:59.999  10437.15   8.907725
19  2007-10-01  2007-12-31 23:59:59.999  10849.78  10.824788
20  2008-01-01  2008-03-31 23:59:59.999  10947.90   8.848333
21  2008-04-01  2008-06-30 23:59:59.999  11047.35   7.999449
22  2008-07-01  2008-09-30 23:59:59.999  11104.22   6.391304
23  2008-10-01  2008-12-31 23:59:59.999  11064.87   1.982437
24  2009-01-01  2009-03-31 23:59:59.999  10965.61   0.161766
25  2009-04-01  2009-06-30 23:59:59.999  11578.02   4.803595
26  2009-07-01  2009-09-30 23:59:59.999  11867.18   6.870901
27  2009-10-01  2009-12-31 23:59:59.999  12019.46   8.627214
28  2010-01-01  2010-03-31 23:59:59.999  12385.69  12.950306
29  2010-04-01  2010-06-30 23:59:59.999  12759.80  10.207099
30  2010-07-01  2010-09-30 23:59:59.999  13037.89   9.865107
31  2010-10-01  2010-12-31 23:59:59.999  13329.02  10.895331
32  2011-01-01  2011-03-31 23:59:59.999  13610.51   9.888993
33  2011-04-01  2011-06-30 23:59:59.999  13836.57   8.438769
34  2011-07-01  2011-09-30 23:59:59.999  13946.05   6.965544
35  2011-10-01  2011-12-31 23:59:59.999  14151.31   6.169171
36  2012-01-01  2012-03-31 23:59:59.999  14320.53   5.216704
37  2012-04-01  2012-06-30 23:59:59.999  14425.12   4.253583
38  2012-07-01  2012-09-30 23:59:59.999  14620.60   4.836853
39  2012-10-01  2012-12-31 23:59:59.999  14896.50   5.265873
40  2013-01-01  2013-03-31 23:59:59.999  14979.57   4.602064
41  2013-04-01  2013-06-30 23:59:59.999  15075.86   4.511158
42  2013-07-01  2013-09-30 23:59:59.999  15374.32   5.155192
43  2013-10-01  2013-12-31 23:59:59.999  15561.92   4.466955
44  2014-01-01  2014-03-31 23:59:59.999  15865.85   5.916592
45  2014-04-01  2014-06-30 23:59:59.999  15985.67   6.034880
46  2014-07-01  2014-09-30 23:59:59.999  16299.59   6.018282
47  2014-10-01  2014-12-31 23:59:59.999       NaN        NaN

In [112]:
p = 1
d = 0
q = 0
horizon=2
window = 24
data = india[:47].ygr

In [114]:
# expansion
forecast = []
for i in range(0, len(data)-window+1):
    data_use = data[0:i+window]
    model = ts.arima_model.ARIMA(endog=data_use, order=(p, d, q)).fit()
    horizon_forecast = model.forecast(steps=horizon)
    forecast.append(horizon_forecast[0][horizon-1])
    
result = pd.concat([pd.DataFrame(data[window+horizon-1:]), 
                    pd.DataFrame(forecast[:-horizon], index=pd.DataFrame(data[window+horizon-1:]).index)], 
                   axis=1)
result.rename(columns={"ygr":"actual", 0:"forecast"}, inplace=True)

/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [115]:
result

ygr  forecast
25   4.803595  5.785756
26   6.870901  2.832901
27   8.627214  6.263709
28  12.950306  7.219759
29  10.207099  7.991891
30   9.865107  9.992776
31  10.895331  8.784735
32   9.888993  8.690959
33   8.438769  9.212956
34   6.965544  8.809349
35   6.169171  8.187613
36   5.216704  7.544016
37   4.253583  7.159790
38   4.836853  6.655842
39   5.265873  6.064649
40   4.602064  6.276186
41   4.511158  6.438683
42   5.155192  6.019861
43   4.466955  5.894811
44   5.916592  6.202825
45   6.034880  5.763903
46   6.018282  6.552618

In [116]:
result["AE"] = np.absolute(result.actual-result.forecast)

In [118]:
np.average(result.AE)

1.7381433952037795

In [120]:
p = 1
d = 0
q = 0
horizon=1
window = 24
data = india[:47].ygr

In [123]:
# expansion
forecast = []
for i in range(0, len(data)-window+1):
    data_use = data[0:i+window]
    model = ts.arima_model.ARIMA(endog=data_use, order=(p, d, q)).fit()
    horizon_forecast = model.forecast(steps=horizon)
    forecast.append(horizon_forecast[0][horizon-1])
    
result = pd.concat([pd.DataFrame(data[window+horizon-1:]), 
                    pd.DataFrame(forecast[:-horizon], index=pd.DataFrame(data[window+horizon-1:]).index)], 
                   axis=1)
result.rename(columns={"ygr":"actual", 0:"forecast"}, inplace=True)

/Users/kmiyaki/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [126]:
np.sqrt(mean_squared_error(result.actual, result.forecast))

1.781395487655124

In [127]:
p = 1
d = 0
q = 0
horizon=1
window = 24
data = india[:47].ygr

In [128]:
# rolling
forecast = []
for i in range(0, len(data)-window+1):
    data_use = data[i:i+window]
    model = ts.arima_model.ARIMA(endog=data_use, order=(p, d, q)).fit()
    horizon_forecast = model.forecast(steps=horizon)
    forecast.append(horizon_forecast[0][horizon-1])
    
result = pd.concat([pd.DataFrame(data[window+horizon-1:]), 
                    pd.DataFrame(forecast[:-horizon], index=pd.DataFrame(data[window+horizon-1:]).index)], 
                   axis=1)
result.rename(columns={"ygr":"actual", 0:"forecast"}, inplace=True)

In [129]:
np.sqrt(mean_squared_error(result.actual, result.forecast))

1.7078992318054262

In [131]:
p = 1
d = 0
q = 0
horizon=2
window = 24
data = india[:47].ygr

In [132]:
# rolling
forecast = []
for i in range(0, len(data)-window+1):
    data_use = data[i:i+window]
    model = ts.arima_model.ARIMA(endog=data_use, order=(p, d, q)).fit()
    horizon_forecast = model.forecast(steps=horizon)
    forecast.append(horizon_forecast[0][horizon-1])
    
result = pd.concat([pd.DataFrame(data[window+horizon-1:]), 
                    pd.DataFrame(forecast[:-horizon], index=pd.DataFrame(data[window+horizon-1:]).index)], 
                   axis=1)
result.rename(columns={"ygr":"actual", 0:"forecast"}, inplace=True)

In [133]:
result["AE"] = np.absolute(result.actual-result.forecast)

In [134]:
np.average(result.AE)

1.643017678494302

## Session 7 Workshop Questions: Fan Charts in EViews

Open the Module 4 Workfile and go to the Thailand_M pagefile. We will use the Fan Charts Program file as well. As mentioned in lecture, you can change the model to your own specifications by changing the equation in the main program.

Let’s apply the code to create a fan chart for an AR(1) model. Specify the model as such (line 29). Set the sample for estimation to be the entire dataset up to December 2012 ("@first 2012m12") and let’s construct the fan chart for 2013 ("2013m1 2013m12"). For now assume that the errors are bootstrapped, and there is coefficient uncertainty. Make a fan chart for 2013 with 3 bands (for 30, 60 and 90% confidence).

Because construction of a fan chart relies on the EViews random number generator, please rerun the program if your confidence bands do not look smooth. This is an artifact of a specific sequence of random draws.

In [137]:
thailand = pd.read_csv("data/M4_data.csv")

In [139]:
data = thailand[:120]
data.tail()

date   cpi
115   8/31/12  2.76
116   9/30/12  3.38
117  10/31/12  3.27
118  11/30/12  2.66
119  12/31/12  3.55

In [140]:
model = ts.arima_model.ARIMA(endog=data.cpi, order=(1, 0, 0)).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              ARMA Model Results                              
==============================================================================
Dep. Variable:                    cpi   No. Observations:                  120
Model:                     ARMA(1, 0)   Log Likelihood                -136.264
Method:                       css-mle   S.D. of innovations              0.747
Date:                Wed, 13 Nov 2019   AIC                            278.529
Time:                        11:57:49   BIC                            286.891
Sample:                             0   HQIC                           281.925
                                                                              
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.0561      0.856      3.570      0.001       1.378       4.734
ar.L1.cpi      0.9277      0.031     29.845      0.000       0.867       0.989
                                    Roots                                    
=============================================================================
                  Real          Imaginary           Modulus         Frequency
-----------------------------------------------------------------------------
AR.1            1.0779           +0.0000j            1.0779            0.0000
-----------------------------------------------------------------------------
"""

In [144]:
model.forecast(steps=12, alpha = 0.1)

(array([3.51428208, 3.481147  , 3.45040799, 3.42189178, 3.39543763,
        3.37089644, 3.34812988, 3.32700961, 3.30741659, 3.28924038,
        3.27237853, 3.256736  ]),
 array([0.74705772, 1.01901654, 1.2048829 , 1.34442262, 1.45382758,
        1.54177894, 1.61363685, 1.6730089 , 1.72246708, 1.76392112,
        1.79883199, 1.82834284]),
 array([[2.28548149, 4.74308268],
        [1.80501395, 5.15728006],
        [1.46855199, 5.432264  ],
        [1.21051336, 5.6332702 ],
        [1.00410407, 5.7867712 ],
        [0.83489576, 5.90689713],
        [0.69393345, 6.0023263 ],
        [0.57515484, 6.07886437],
        [0.47421036, 6.14062282],
        [0.38784833, 6.19063244],
        [0.31356321, 6.23119386],
        [0.24937965, 6.26409236]]))

In [145]:
model.forecast(steps=12, alpha = 0.4)

(array([3.51428208, 3.481147  , 3.45040799, 3.42189178, 3.39543763,
        3.37089644, 3.34812988, 3.32700961, 3.30741659, 3.28924038,
        3.27237853, 3.256736  ]),
 array([0.74705772, 1.01901654, 1.2048829 , 1.34442262, 1.45382758,
        1.54177894, 1.61363685, 1.6730089 , 1.72246708, 1.76392112,
        1.79883199, 1.82834284]),
 array([[2.88554245, 4.14302172],
        [2.62352104, 4.33877296],
        [2.43635296, 4.46446302],
        [2.29039716, 4.5533864 ],
        [2.17186547, 4.61900979],
        [2.07330255, 4.66849034],
        [1.99005884, 4.70620091],
        [1.91896979, 4.73504943],
        [1.85775172, 4.75708146],
        [1.80468691, 4.77379385],
        [1.75844333, 4.78631373],
        [1.71796384, 4.79550816]]))

In [146]:
model.forecast(steps=12, alpha = 0.7)

(array([3.51428208, 3.481147  , 3.45040799, 3.42189178, 3.39543763,
        3.37089644, 3.34812988, 3.32700961, 3.30741659, 3.28924038,
        3.27237853, 3.256736  ]),
 array([0.74705772, 1.01901654, 1.2048829 , 1.34442262, 1.45382758,
        1.54177894, 1.61363685, 1.6730089 , 1.72246708, 1.76392112,
        1.79883199, 1.82834284]),
 array([[3.22642546, 3.80213871],
        [3.08849907, 3.87379493],
        [2.98614195, 3.91467403],
        [2.90385823, 3.93992533],
        [2.83524811, 3.95562715],
        [2.77681746, 3.96497542],
        [2.72636257, 3.96989718],
        [2.68236504, 3.97165418],
        [2.64371477, 3.97111841],
        [2.60956547, 3.96891529],
        [2.57925175, 3.96550532],
        [2.55223809, 3.96123392]]))

In [148]:
thailand.iloc[131]

date    12/31/13
cpi         1.66
Name: 131, dtype: object

In [149]:
thailand.iloc[143]

date    12/31/14
cpi         0.62
Name: 143, dtype: object